- name: install multiple packages
  hosts: all
  tasks:
    - name: install packages
      ansible.builtin.yum:
        name:
          - httpd
          - nginx
        state: present
        enabled: yes