- name: install multiple packages
  hosts: all
  tasks:
    - name: install packages
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: start the service
        enabled: yes