- name: install package
  hosts: all
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: start the service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

