- name: install package
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      ansible.yum.package:
        name: nginx
        state: present
    - name: start the service
      ansible.systemd.service:
        name: nginx
        state: started

