- name: declare a variable from play
  hosts: all
  connection: local
  vars:
    URL: play.online.com
  tasks:
    - name: call a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable from task
  hosts: all
  connection: local
  tasks:
    - name: call a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.online.com

- name: declare a variable from file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: call a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable from fact
  hosts: all
  connection: local
  tasks:
    - name: call a fact
      ansible.builtin.debug:
        msg: ansible host name == {{ansible_fqdn}}}
- name: register a variable
  hosts: all
  connection: local
  tasks:
    - name: run a shell command
      ansible.builtin.shell: uptime
      register: OUT
    - name: call register
      ansible.builtin.debug:
        msg: "{{OUT}}"